<div class="block tcg-wishlist" style="float: right;margin-bottom: 0.5%;margin-top: 0.5%;">
    <?php 
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

        $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
        
        $baseurl = $storeManager->getStore()->getBaseUrl();
    ?>
    <a href="<?php echo $baseurl.'/wishlist'; ?>"><i class="far fa-heart"></i></a>


</div>