<?php
    $_config = $this->helper('Sm\Themecore\Helper\Data');
?>

<div class="header-container header-style-1">
    <!-- removed header middle part -->
    <div class="header-wrapper bg-orange p-2 text-white">
        <div class="container">
            <div class="row d-flex justify-content-between align-items-center">    
                <div class="">
                    <div class="header-info">
                        info@toucango.com.au
                    </div>
                </div>
                <div class="">
                    <div class="header-icons d-flex">
                        <div class="wishlist px-3 b-separator-right b-color-white">
                            <i class="fas fa-heart"></i>
                        </div>
                        <div class="cart px-3 b-separator-right b-color-white">
                            <div class="minicart-header" data-move="minicart-mobile">
                                <?php echo $this->getChildHtml("minicart"); ?>
                            </div>
                        </div>
                        <div class="block-right account px-3">
                            <div class="block-content" data-move="customer-mobile">
                                <?php echo $this->getChildHtml("header.links"); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
    <div class="header-bottom ontop-element">
        <div class="container">
            <div class="row">
                <div class="middle-content">
                    <div class="logo-container">
                        <?php echo $this->getChildHtml("logo"); ?>
                    </div>
                </div>
                <div class="desktop-menu">
                    <div class="horizontal-block">
                        <?php
                        if ($_config->getGeneral('navigation_group/menu_style') == 'megamenu') {
                            echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
                        } else {
                            echo $this->getChildHtml("horizontal-css");
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
