<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js" > </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fabric.js/1.4.8/fabric.min.js" > </script>
    <script src="<?php echo $this->getViewFileUrl('Magenest_GiftCard::js/design/fabric/angular.js')  ?>" > </script>
    <script src= "<?php echo $this->getViewFileUrl('Magenest_GiftCard::js/design/fabric.js')  ?>"  > </script>

    <script src= "<?php echo $this->getViewFileUrl('Magenest_GiftCard::js/design/fabricCanvas.js')  ?>" > </script>

    <script  src= "<?php echo $this->getViewFileUrl('Magenest_GiftCard::js/design/fabricConstants.js') ?> "  ></script>
    <script  src= "<?php echo $this->getViewFileUrl('Magenest_GiftCard::js/design/fabricDirective.js') ?> " src="https://rawgithub.com/clouddueling/angular-fabric/master/assets/fabricDirective.js" ></script>
    <script  src= "<?php echo $this->getViewFileUrl('Magenest_GiftCard::js/design/fabricDirtyStatus.js') ?> " src="https://rawgithub.com/clouddueling/angular-fabric/master/assets/fabricDirtyStatus.js" ></script>
    <script   src= "<?php echo $this->getViewFileUrl('Magenest_GiftCard::js/design/fabricUtilities.js') ?> "src="https://rawgithub.com/clouddueling/angular-fabric/master/assets/fabricUtilities.js" ></script>
    <script  src= "<?php echo $this->getViewFileUrl('Magenest_GiftCard::js/design/fabricWindow.js') ?> " src="https://rawgithub.com/clouddueling/angular-fabric/master/assets/fabricWindow.js" ></script>
    <script  src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" ></script>


    <link  href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"  rel="stylesheet" type="text/css"  media="all" />
    <link   href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"  rel="stylesheet" type="text/css"  media="all" />
    <link   href="<?php echo $this->getViewFileUrl('Magenest_GiftCard::css/design/style.css') ?>   rel="stylesheet" type="text/css"  media="all" />

    <style>
        .built-in-art {
            width: 50px;
            height: 60px;
            display: inline-block;
            margin-left: 6px;
            margin-top: 6px;
            padding: 5px;
            cursor: pointer;
        }
        .built-in-art img {
            width: 100%;
            height: 100%;
        }

        body {
            padding-bottom: 10px;
            padding-left: 10px;
            padding-right: 10px;
            padding-top: 10px;
        }
        .image-builder-container {
            position: relative;
        }
        .image-builder-container .image-builder {
            -moz-border-bottom-colors: none;
            -moz-border-left-colors: none;
            -moz-border-right-colors: none;
            -moz-border-top-colors: none;
            background-attachment: scroll;
            background-clip: border-box;
            background-color: #cacaca;
            background-image: none;
            background-origin: padding-box;
            background-position: 0 0;
            background-repeat: repeat;
            background-size: auto auto;
            border-bottom-color: #cacaca;
            border-bottom-style: solid;
            border-bottom-width: 1px;
            border-image-outset: 0 0 0 0;
            border-image-repeat: stretch stretch;
            border-image-slice: 100% 100% 100% 100%;
            border-image-source: none;
            border-image-width: 1 1 1 1;
            border-left-color: #cacaca;
            border-left-style: solid;
            border-left-width: 1px;
            border-right-color: #cacaca;
            border-right-style: solid;
            border-right-width: 1px;
            border-top-color: #cacaca;
            border-top-style: solid;
            border-top-width: 1px;
            box-sizing: border-box;
            min-height: 460px;
            overflow-x: scroll;
            overflow-y: hidden;
            position: relative;
            text-align: center;
            width: auto;
        }
        .image-builder-container .image-builder .image-cover {
            bottom: 0;
            left: 0;
            position: absolute;
            right: 0;
            top: 0;
            z-index: 2;
        }
        .image-builder-container .image-builder .fabric-container {
            background-attachment: scroll;
            background-clip: border-box;
            background-color: white;
            background-image: none;
            background-origin: padding-box;
            background-position: 0 0;
            background-repeat: repeat;
            background-size: auto auto;
            border-bottom-left-radius: 1px;
            border-bottom-right-radius: 1px;
            border-top-left-radius: 1px;
            border-top-right-radius: 1px;
            box-shadow: 0 1px 4px -1px rgba(0, 0, 0, 0.4);
            display: inline-block;
            margin-bottom: 50px;
            margin-left: 50px;
            margin-right: 50px;
            margin-top: 50px;
            position: relative;
            vertical-align: middle;
            z-index: 0;
        }
        .image-builder-container .image-loading {
            background-attachment: scroll;
            background-clip: border-box;
            background-color: rgba(255, 255, 255, 0.4);
            background-image: none;
            background-origin: padding-box;
            background-position: 0 0;
            background-repeat: repeat;
            background-size: auto auto;
            bottom: 0;
            left: 0;
            position: absolute;
            right: 0;
            top: 0;
            z-index: 1;
        }
        .image-builder-container .image-loading .loading-indicator {
            background-attachment: scroll;
            background-clip: border-box;
            background-color: white;
            background-image: url("/images/squareLoader.gif");
            background-origin: padding-box;
            background-position: center center;
            background-repeat: no-repeat;
            background-size: auto auto;
            border-bottom-left-radius: 10px;
            border-bottom-right-radius: 10px;
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.2);
            height: 160px;
            margin-bottom: 0;
            margin-left: auto;
            margin-right: auto;
            margin-top: 300px;
            width: 160px;
        }
        .image-builder-container .object-controls-container {
            position: relative;
        }
        .image-builder-container .object-controls-container .object-controls {
            background-attachment: scroll;
            background-clip: border-box;
            background-color: white;
            background-image: none;
            background-origin: padding-box;
            background-position: 0 0;
            background-repeat: repeat;
            background-size: auto auto;
            left: -250px;
            padding-bottom: 5px;
            padding-left: 5px;
            padding-right: 5px;
            padding-top: 5px;
            position: absolute;
            top: 0;
            width: 240px;
            z-index: 1;
        }
        .image-builder-container .object-controls-container .object-controls textarea {
            font-size: 12px;
        }
        .object-font-family-preview {
            text-transform: capitalize;
        }

    </style>
</head>
<body>

<div ng-app='example' ng-controller="ExampleCtrl">
    <div class='image-builder-container container-fluid'>
        <div ng-if="fabric.isLoading()" class="image-loading">
            <div class="loading-indicator"></div>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <br />
                <div class='btn-group pull-left mrm'>
                    <button ng-disabled="!fabric.selectedObject" ng-click="fabric.deleteActiveObject(); fabric.setDirty(true)" class='btn btn-danger'>
                        <i class='fa fa-trash-o'></i>
                        <div class='clearfix'></div>
                        <?php echo __("Delete") ?>
                    </button>

                    <button ng-click='fabric.addBackground()' class='btn btn-default'>
                        <i class='fa fa-image'></i>
                        <div class='clearfix'></div>
                        <?php echo __('Background')  ?>
                    </button>

                    <button ng-click="fabric.addText()" class='btn btn-default'>
                        <i class='fa fa-font'></i>
                        <div class='clearfix'></div>
                        &nbsp; <?php echo __("Text") ?> &nbsp;
                    </button>

                    <button ng-click='fabric.addArt()' class='btn btn-default'>
                        <i class='fa fa-star'></i>
                        <div class='clearfix'></div>
                        <?php echo __("Add Art")  ?>
                    </button>

                    <button ng-click="fabric.clearCanvas(); fabric.setDirty(true)" class='btn btn-default'>
                        <i class='fa fa-refresh'></i>
                        <div class='clearfix'></div>
                        <?php echo __("Restart")  ?>
                    </button>
                </div>

                <div class='pull-left' style='margin: 15px 0 0 10px;'>
                    <div class='row'>
                        <div class='col-xs-1 text-center'>
                            <i class='fa fa-search-minus pull-left'></i>
                        </div>
                        <div class='col-xs-6'>
                            <input type='range' class='pull-left' min='.1' max='3' step='.1' ng-change='fabric.setZoom()' ng-model='fabric.canvasScale' />
                        </div>
                        <div class='col-xs-1 text-center'>
                            <i class='fa fa-search-plus'></i>
                        </div>
                        <div class='col-xs-3'>
                            <button class='btn btn-xs' ng-click="fabric.resetZoom()">
                                <?php echo __("Reset") ?>
                            </button>
                        </div>
                    </div>
                </div>

                <div class="pull-right">
                    <button class='btn btn-default'  ng-click="fabric.submitDesign('myCanvas')"title='This is where you would take the json from the canvas and save it to your database.'>
                        <i class='fa fa-save'></i>
                        <div class='clearfix'></div>
                        <?php echo __("Save") ?> <span ng-show='fabric.isDirty()' class='text-danger'>*</span>
                    </button>
                    <button class='btn btn-default'  ng-click="fabric.openGiftCardOption('myCanvas')" title='Open Gift card option'>
                        <i class='fa fa-option'></i>
                        <div class='clearfix'></div>
                        <?php echo __("Gift card option") ?> <span ng-show='fabric.isDirty()' class='text-danger'>*</span>
                    </button>

                    <button ng-click="fabric.download('myCanvas')" class='btn btn-success'>
                        <i class='fa fa-download'></i>
                        <div class='clearfix'></div>
                        <?php echo __("Download")  ?>
                    </button>
                </div>
            </div>
        </div>

        <br />

        <div class="row">
            <div class="col-xs-4">
                <label><?php echo  __("Background Color")  ?></label>
                <input type="text" class='form-control' ng-change='fabric.setDirty(true); fabric.stopContinuousRendering()' ng-model="fabric.canvasBackgroundColor" />
            </div>

        </div>

        <br />

        <div class='row'>
            <div class='col-xs-3'>
                <div ng-switch='fabric.selectedObject.type'>
                    <div ng-switch-when='changebackground'>
                        <span><?php echo __("Background") ?></span>


                        <div class="definedArt">
                            <!--- define the background-->
                            <?php
                            if  ($background) {
                                foreach ($background as $bg) {
                                    ?>
                                    <div class="built-in-art">
                                        <img src="<?php echo $bg['file']?>" title="<?php echo $bg['title']?>" ng-click="fabric.setBGImage('<?php echo $bg['file']?>')" />
                                    </div>
                                <?php
                                }
                            }
                            ?>

                        </div>
                    </div>
                    <div ng-switch-when='uploadimage'>
                        <span><?php echo __("Art") ?></span>
                        <input type="file" name="art">


                        <div> <button i="uploadArt"> <?php echo __("Upload")  ?></button></div>
                        <div class="definedArt">
                            <?php
                            if ($art) {
                                foreach ($art as $theArt) {
                                ?>
                                    <div class="built-in-art">
                                        <img src="<?php echo $theArt['file'] ?>" title="<?php echo $theArt['title'] ?>" ng-click="fabric.addArt('<?php echo $theArt['file'] ?>')" />
                                    </div>
                            <?php
                                }
                            }
                            ?>

                        </div>
                    </div>
                </div>

                <div ng-if='fabric.selectedObject'>
                    <div ng-switch='fabric.selectedObject.type'>
                        <div ng-switch-when='text'>
                            <p>
                                <textarea style="text-align: {{ fabric.selectedObject.textAlign }}" class="form-control" rows="6" ng-model="fabric.selectedObject.text"></textarea>
                            </p>

                            <p title="Font size">
                                <i class="fa fa-text-height"></i>
                                <input type='number' class="form-control" ng-model="fabric.selectedObject.fontSize" />
                            </p>

                            <p title="Line height">
                                <i class="fa fa-align-left"></i>
                                <input type='number' class="form-control" ng-model="fabric.selectedObject.lineHeight" step=".1" />
                            </p>

                            <div class='btn-group'>
                                <button ng-class="{ active: fabric.selectedObject.textAlign == 'left' }" ng-click="fabric.selectedObject.textAlign = 'left'" class='btn btn-small'>
                                    <i class='fa fa-align-left'></i>
                                </button>

                                <button ng-class="{ active: fabric.selectedObject.textAlign == 'center' }" ng-click="fabric.selectedObject.textAlign = 'center'" class='btn btn-small'>
                                    <i class='fa fa-align-center'></i>
                                </button>

                                <button ng-class="{ active: fabric.selectedObject.textAlign == 'right' }" ng-click="fabric.selectedObject.textAlign = 'right'" class='btn btn-small'>
                                    <i class='fa fa-align-right'></i>
                                </button>
                            </div>

                            <br />

                            <div class='btn-group'>
                                <button ng-class="{ active: fabric.isBold() }" ng-click="fabric.toggleBold()" class='btn btn-small'>
                                    <i class='fa fa-bold'></i>
                                </button>

                                <button ng-class="{ active: fabric.isItalic() }" ng-click="fabric.toggleItalic()" class='btn btn-small'>
                                    <i class='fa fa-italic'></i>
                                </button>

                                <button ng-class="{ active: fabric.isUnderline() }" ng-click="fabric.toggleUnderline()" class='btn btn-small'>
                                    <i class='fa fa-underline'></i>
                                </button>

                                <button ng-class="{ active: fabric.isLinethrough() }" ng-click="fabric.toggleLinethrough()" class='btn btn-small'>
                                    <i class='fa fa-strikethrough'></i>
                                </button>
                            </div>

                            <br />

                            <div class="row">
                                <div class="btn-group col-sm-12">
                                    <a class="btn btn-default btn-block dropdown-toggle" data-toggle="dropdown" href="#">
                    <span class='object-font-family-preview' style='font-family: "{{ fabric.selectedObject.fontFamily }}";'>
                      {{ fabric.selectedObject.fontFamily }}
                    </span>
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li ng-repeat='font in FabricConstants.fonts' ng-click='fabric.selectedObject.fontFamily = font.name' style='font-family: "{{ font.name }}";'>
                                            <a>{{ font.name }}</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div ng-switch-when="image">
                            <div class="input-prepend">
                                <button ng-class="{ active: fabric.isTinted() }" ng-click="fabric.toggleTint()" class='btn'>
                                    <i class='fa fa-tint'></i>
                                </button>
                                <input type="text" class='input-small' ng-model='fabric.selectedObject.tint' />
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <input class='col-sm-12' title="Transparency" type='range'
                                   min="0"
                                   max="1"
                                   step=".01"
                                   ng-model="fabric.selectedObject.opacity" />
                        </div>
                    </div>

                    <div class="row mbm">
                        <div class="col-sm-12">
                            <button class='btn btn-small btn-block' ng-class="{ active: fabric.getFlipX() }" ng-click="{ active: fabric.toggleFlipX() }">
                                <i class='fa fa-exchange'></i> <?php echo __("Flip") ?>
                            </button>
                        </div>
                    </div>

                    <div class="row" ng-hide="fabric.selectedObject.type == 'image'">
                        <div class="col-sm-12">
                            <input type="text" class='form-control' ng-model="fabric.selectedObject.fill" />
                        </div>
                    </div>

                    <div class="row">
                        <div class="btn-group col-xs-12 btn-group-vertical">
                            <button ng-click='fabric.center()' class='btn btn-small btn-block'>
                                <?php echo __("Center") ?>
                            </button>

                            <button ng-click='fabric.centerH()' class='btn btn-small btn-block'>
                                <?php echo __("Center Horizontally")  ?>
                            </button>

                            <button ng-click='fabric.centerV()' class='btn btn-small btn-block'>
                                <?php echo __("Center Vertically") ?>
                            </button>
                        </div>
                    </div>

                    <br />

                    <div class="row">
                        <div class="btn-group col-xs-12 btn-group-vertical">
                            <button ng-click='fabric.bringToFront(); fabric.setDirty(true)' class='btn btn-small btn-block'>
                                <?php echo __("Bring to front")  ?>
                            </button>

                            <button ng-click='fabric.bringForward(); fabric.setDirty(true)' class='btn btn-small btn-block'>
                                <?php echo __("Bring forwards")  ?>
                            </button>

                            <button ng-click='fabric.sendBackwards(); fabric.setDirty(true)' class='btn btn-small btn-block'>
                                <?php echo __("Send backwards") ?>
                            </button>

                            <button ng-click='fabric.sendToBack(); fabric.setDirty(true)' class='btn btn-small btn-block'>
                                <?php echo __("Send to back") ?>
                            </button>
                        </div>
                    </div>

                    <br />

                    <button ng-click='fabric.toggleLockActiveObject(); fabric.setDirty(true)' ng-class="{ active: fabric.selectedObject.lockObject }" class='btn btn-small btn-block'>
                        <?php echo __("Lock") ?>
                    </button>
                </div>
            </div>

            <div class='col-xs-9'>
                <div class='image-builder' parent-click="fabric.deactivateAll()">
                    <div class='fabric-container'>
                        <canvas fabric='fabric'></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript"  >
    var fabricApp = angular.module('example', [
        'common.fabric',
        'common.fabric.utilities',
        'common.fabric.constants'
    ])

        .controller('ExampleCtrl', ['$scope', 'Fabric', 'FabricConstants', 'Keypress', function($scope, Fabric, FabricConstants, Keypress) {

            $scope.fabric = {};
            $scope.FabricConstants = FabricConstants;

            //
            // Creating Canvas Objects
            // ================================================================
            $scope.addShape = function(path) {
                $scope.fabric.addShape('http://fabricjs.com/assets/15.svg');
            };

            $scope.addImage = function(image) {
                $scope.fabric.addImage('http://127.0.0.1/fa/example/daniel-season-nine.jpg');
            };

            $scope.addImageUpload = function(data) {
                var obj = angular.fromJson(data);
                $scope.addImage(obj.filename);
            };

            //
            // Editing Canvas Size
            // ================================================================
            $scope.selectCanvas = function() {
                $scope.canvasCopy = {
                    width: $scope.fabric.canvasOriginalWidth,
                    height: $scope.fabric.canvasOriginalHeight
                };
            };

            $scope.setCanvasSize = function() {
                $scope.fabric.setCanvasSize($scope.canvasCopy.width, $scope.canvasCopy.height);
                $scope.fabric.setDirty(true);
                delete $scope.canvasCopy;
            };

            //
            // Init
            // ================================================================
            $scope.init = function() {
                $scope.fabric = new Fabric({
                    JSONExportProperties: FabricConstants.JSONExportProperties,
                    textDefaults: FabricConstants.textDefaults,
                    shapeDefaults: FabricConstants.shapeDefaults,
                    json: {}
                });
                $scope.fabric.addImage('http://127.0.0.1/fa/example/daniel-season-nine.jpg');

                $scope.fabric.addText('To : Nguyen Thuy Duong');
                $scope.fabric.addText('From : Nguyen Nam Hung');
                $scope.fabric.setBackgroundImage('http://127.0.0.1/magento2.1/pub/static/frontend/Magento/luma/en_US/Magenest_GiftCard/images/bg2.png');

                // var object = new FabricWindow.Text(str, self.textDefaults);
                //object.id = self.createId();

                //self.addObjectToCanvas(object);

                // $scope.fabric.addText('To : Nguyen Thuy Duong');
            };

            $scope.$on('canvas:created', $scope.init);

            Keypress.onSave(function() {
                $scope.updatePage();
            });

        }]);
</script>

<?php /* @escapeNotVerified */ echo $layoutContent ?>

</body>
</html>