<style>
.tcg-category-image-subtitle {
    width: 300px;
    padding: 0 40px;
    font-size: 14px;
    line-height: 20px;
    color: #fff;
}
.tcg-category-image {
    border-radius: 10px;
}
.tcg-category-image-title {
    width: 300px;
    padding: 0 40px;
    font-size: 24px;
    line-height: 32px;
    color: #fff;
}
.tcg-category-image-text {
    position: absolute;
    bottom: 10%;
    font-size: 20px;
    font-weight: 600;
    color: #fff;
    letter-spacing: 1.5px;
}
</style>
<div class="home-page-1 title-block-1 bottom-title" style="padding-top: 20px;">
	<div class="container">
        <div class="big banner">
            <div class="slider-show nav-style-1 nav-position-center dot-style-1 dot-white dot-position-bottom hover-to-show" style="margin-bottom: 20px:">
                <div data-owl="owlslider" data-autoplay="true" data-nav="true" data-dots="true" data-screen0="1" data-screen481="1" data-screen768="1" data-screen992="1" data-
                screen1200="1" data-screen1441="1" data-screen1681="1" data-screen1920="1" data-margin="1" data-autoplayhoverpause="true" data-loop="true" data-center="false" data-
                stagepadding="0" data-mousedrag="true" data-touchdrag="true">
                    <div class="owl-carousel owl-theme">
                        <div class="item"><a title="Slide 1" href="#"><img src="{{media url="wysiwyg/slidershow/home-1/item-1.jpg"}}" alt="Slide Image" width="1170" height="1170"></a></div>
                        <div class="item"><a title="Slide 2" href="#"><img src="{{media url="wysiwyg/slidershow/home-1/item-2.jpg"}}" alt="Slide Image" width="1170" height="1170"></a></div>
                        <div class="item"><a title="Slide 3" href="#"><img src="{{media url="wysiwyg/slidershow/home-1/item-3.jpg"}}" alt="Slide Image" width="1170" height="1170"></a></div>
                    </div>
                    <div class="loading-content"><span class="hidden">Loading...</span></div>
                </div>
            </div>    
        </div>
		<div class="list-services" style="margin-bottom: 40px;">
            <div data-owl="owl-slider" data-autoplay="true" data-nav="false" data-dots="false" data-screen0="1" data-screen481="1" data-screen768="2" data-screen992="3" data-screen1200="4" data-screen1441="4" data-screen1681="4" data-screen1920="4" data-margin="30" data-autoplayhoverpause="true" data-loop="false" data-center="false" data-stagepadding="0" data-mousedrag="true" data-touchdrag="true">
                <div class="owl-carousel owl-theme">
                    <div class="item">
                        <div class="sv-icon">
                            <img src="{{media url="wysiwyg/services/item-1.png"}}" alt="Slide Image" width="57" height="57">
                        </div>
                        
                        <div class="sv-info">
                            <div class="top-sv">Free Shipping</div>
                            <div class="bottom-sv">on orders over $49</div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="sv-icon">
                            <img src="{{media url="wysiwyg/services/item-2.png"}}" alt="Slide Image" width="57" height="57">
                        </div>
                        
                        <div class="sv-info">
                            <div class="top-sv">Money Guarantee</div>
                            <div class="bottom-sv">30 days money back</div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="sv-icon">
                            <img src="{{media url="wysiwyg/services/item-3.png"}}" alt="Slide Image" width="57" height="57">
                        </div>
                        
                        <div class="sv-info">
                            <div class="top-sv">Online Support</div>
                            <div class="bottom-sv">24/24h on day</div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="sv-icon">
                            <img src="{{media url="wysiwyg/services/item-4.png"}}" alt="Slide Image" width="57" height="57">
                        </div>
                        
                        <div class="sv-info">
                            <div class="top-sv">Gift Promotion</div>
                            <div class="bottom-sv">For all first guest</div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
		
		<div class="slider-product-home" style="margin-bottom: 20px;">
			<div class="stagepadding-slider nav-style-2">
				<div data-owl="owl-slider" data-autoplay="false" data-nav="true" data-dots="false" data-screen0="1" data-screen481="2" data-screen768="3" data-screen992="3" data-screen1200="4" data-screen1441="4" data-screen1681="4" data-screen1920="4" data-margin="30" data-autoplayhoverpause="true" data-loop="false" data-center="false" data-stagepadding="15" data-mousedrag="true" data-touchdrag="true">
					{{block class="Sm\FilterProducts\Block\FilterProducts" template="Sm_FilterProducts::slider.phtml" title_module="Deal Of The Day" product_source="special_products" select_category="4,5,6,14,15,16,17,18,19,23,24,25,26,27,28,34,35,36,40,6,30,31,32,33,37,41" product_limitation="6" display_countdown="1" date_to=""}}
				</div>
			</div>
		</div>


		<div class="blocks-promo">&nbsp;</div>
            <div class="content-heading">
                <h2 class="title">Trending Now</h2>
                <p class="info">Here is what's hot on Toucango right now!</p>
            </div>
            <div class="trending-container col-sm-12">
            <div class="row">
                <div class="tcg-category-image-container col-sm-4 mb-5">
                <img class="tcg-category-image" src="{{media url="wysiwyg/RB-distress-quilt-tile-720x466-winery.jpg"}}" alt="">
                <div class="tcg-category-image-text">
                        <div class="tcg-category-image-title">Experience for 2</div>
                        <div class="tcg-category-image-subtitle">Find new enjoy together later</div>
                </div>
                </div>
                <div class="tcg-category-image-container col-sm-4 mb-5">
                <img class="tcg-category-image" src="{{media url=&quot;wysiwyg/RB-distress-quilt-tile-720x466-whaleshark.jpg&quot;}}" alt="" />
                <div class="tcg-category-image-text">
                        <div class="tcg-category-image-title">Birthday Gifts</div>
                        <div class="tcg-category-image-subtitle">Gift ideas to look forward to</div>
                </div>
                </div>
                <div class="tcg-category-image-container col-sm-4 mb-5">
                <img class="tcg-category-image" src="{{media url=&quot;wysiwyg/Quilt-New-Voucher.jpg&quot;}}" alt="" />
                <div class="tcg-category-image-text">
                        <div class="tcg-category-image-title">Gift vouchers</div>
                        <div class="tcg-category-image-subtitle">Gift the gift of choice</div>
                </div>
                </div>
            </div>
        </div>


        <div class="blocks-promo">&nbsp;</div>
        <div class="content-heading">
            <h2 class="title">Popular categories</h2>
            <p class="info">Indulge. Explore. Connect. Unwind. Escape.</p>
        </div>	
		<div class="trending-container col-sm-12">
            <div class="row">
                <div class="tcg-category-image-container col-sm-4 mb-5">
                    <img class="tcg-category-image" src="{{media url="wysiwyg/RB-distress-quilt-tile-720x466-winery.jpg"}}" alt="">
                    <div class="tcg-cateory-image-text">
                        <div class="tcg-category-image-title">Experience for 2</div>
                        <div class="tcg-category-image-subtitle">Find new enjoy together later</div>
                    </div>
                </div>
                <div class="tcg-category-image-container col-sm-4 mb-5">
                    <img class="tcg-category-image" src="{{media url=&quot;wysiwyg/RB-distress-quilt-tile-720x466-whaleshark.jpg&quot;}}" alt="" />
                    <div class="tcg-category-image-text">
                        <div class="tcg-category-image-title">Birthday Gifts</div>
                        <div class="tcg-category-image-subtitle">Gift ideas to look forward to</div>
                    </div>
                </div>
                <div class="tcg-category-image-container col-sm-4 mb-5">
                    <img class="tcg-category-image" src="{{media url=&quot;wysiwyg/Quilt-New-Voucher.jpg&quot;}}" alt="" />
                    <div class="tcg-category-image-text">
                        <div class="tcg-category-image-title">Gift vouchers</div>
                        <div class="tcg-category-image-subtitle">Gift the gift of choice</div>
                    </div>
                </div>
            </div>
        </div>

		<div class="slider-product-home" style="margin-bottom: 20px;">
			<div class="stagepadding-slider nav-style-2">
				<div data-owl="owl-slider" data-autoplay="false" data-nav="true" data-dots="false" data-screen0="1" data-screen481="2" data-screen768="3" data-screen992="3" data-screen1200="4" data-screen1441="4" data-screen1681="4" data-screen1920="4" data-margin="30" data-autoplayhoverpause="true" data-loop="false" data-center="false" data-stagepadding="15" data-mousedrag="true" data-touchdrag="true">
					{{block class="Sm\FilterProducts\Block\FilterProducts" template="Sm_FilterProducts::slider.phtml" title_module="Best Sellers" product_source="best_sellers" select_category="4,5,6,14,15,16,17,18,19,23,24,25,26,27,28,34,35,36,40,6,30,31,32,33,37,41" product_limitation="6" display_countdown="0" date_to=""}}
				</div>
			</div>
		</div>

		<div class="slider-product-home" style="margin-bottom: 20px;">
			<div class="stagepadding-slider nav-style-2">
				<div data-owl="owl-slider" data-autoplay="false" data-nav="true" data-dots="false" data-screen0="1" data-screen481="2" data-screen768="3" data-screen992="3" data-screen1200="4" data-screen1441="4" data-screen1681="4" data-screen1920="4" data-margin="30" data-autoplayhoverpause="true" data-loop="false" data-center="false" data-stagepadding="15" data-mousedrag="true" data-touchdrag="true">
					{{block class="Sm\FilterProducts\Block\FilterProducts" template="Sm_FilterProducts::slider.phtml" title_module="Winter is here" product_source="other_products" select_category="4,5,6,14,15,16,17,18,19,23,24,25,26,27,28,34,35,36,40,6,30,31,32,33,37,41" product_limitation="6" display_countdown="0" date_to=""}}
				</div>
			</div>
		</div>

		<div class="banner-bottom">
			<div class="banner-image" style="margin-bottom: 40px;">
				<a href="#"><img class="mark-lazy" src="{{media url="wysiwyg/banner/item-6.jpg"}}" alt="Banner Image" width="1170" height="130"></a>
			</div>
		</div>
		
		<div class="group-product-list">
			<div class="row">
				<div class="col-lg-4">
					<div class="nav-style-2" style="margin-bottom: 50px;">
						<div data-owl="owl-slider" data-autoplay="false" data-nav="true" data-dots="false" data-screen0="1" data-screen481="1" data-screen768="1" data-screen992="1" data-screen1200="1" data-screen1441="1" data-screen1681="1" data-screen1920="1" data-margin="30" data-autoplayhoverpause="true" data-loop="false" data-center="false" data-stagepadding="0" data-mousedrag="true" data-touchdrag="true">
							{{block class="Sm\FilterProducts\Block\FilterProducts" template="Sm_FilterProducts::list-slider.phtml" row_items="3" title_module="New Arrivals" product_source="lastest_products" select_category="4,5,6,14,15,16,17,18,19,23,24,25,26,27,28,34,35,36,40,6,30,31,32,33,37,41" product_limitation="6" display_countdown="0" date_to=""}}
						</div>
					</div>
				</div>
				
				<div class="col-lg-4">
					<div class="nav-style-2" style="margin-bottom: 50px;">
						<div data-owl="owl-slider" data-autoplay="false" data-nav="true" data-dots="false" data-screen0="1" data-screen481="1" data-screen768="1" data-screen992="1" data-screen1200="1" data-screen1441="1" data-screen1681="1" data-screen1920="1" data-margin="30" data-autoplayhoverpause="true" data-loop="false" data-center="false" data-stagepadding="0" data-mousedrag="true" data-touchdrag="true">
							{{block class="Sm\FilterProducts\Block\FilterProducts" template="Sm_FilterProducts::list-slider.phtml" row_items="3" title_module="Featured Products" product_source="featured_products" select_category="4,5,6,14,15,16,17,18,19,23,24,25,26,27,28,34,35,36,40,6,30,31,32,33,37,41" product_limitation="6" display_countdown="0" date_to=""}}
						</div>
					</div>
				</div>
				
				<div class="col-lg-4">
					<div class="nav-style-2" style="margin-bottom: 50px;">
						<div data-owl="owl-slider" data-autoplay="false" data-nav="true" data-dots="false" data-screen0="1" data-screen481="1" data-screen768="1" data-screen992="1" data-screen1200="1" data-screen1441="1" data-screen1681="1" data-screen1920="1" data-margin="30" data-autoplayhoverpause="true" data-loop="false" data-center="false" data-stagepadding="0" data-mousedrag="true" data-touchdrag="true">
							{{block class="Sm\FilterProducts\Block\FilterProducts" template="Sm_FilterProducts::list-slider.phtml" row_items="3" title_module="Special Products" product_source="special_products" select_category="4,5,6,14,15,16,17,18,19,23,24,25,26,27,28,34,35,36,40,6,30,31,32,33,37,41" product_limitation="6" display_countdown="0" date_to=""}}
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="brand-slider hover-to-show" style="margin-bottom: 40px;">
			<div class="nav-style-3 nav-position-center">
				<div data-owl="owl-slider" data-autoplay="true" data-nav="true" data-dots="false" data-screen0="2" data-screen481="4" data-screen768="5" data-screen992="5" data-screen1200="6" data-screen1441="6" data-screen1681="6" data-screen1920="6" data-margin="20" data-autoplayhoverpause="true" data-loop="false" data-center="false" data-stagepadding="0" data-mousedrag="true" data-touchdrag="true">
					<div class="owl-carousel owl-theme">
						<div class="item"><a title="Brand 1" href="#"><img class="mark-lazy" src="{{media url="wysiwyg/brands/item-1.jpg"}}" alt="Brand Image" width="170" height="100"></a></div>
						<div class="item"><a title="Brand 1" href="#"><img class="mark-lazy" src="{{media url="wysiwyg/brands/item-2.jpg"}}" alt="Brand Image" width="170" height="100"></a></div>
						<div class="item"><a title="Brand 1" href="#"><img class="mark-lazy" src="{{media url="wysiwyg/brands/item-3.jpg"}}" alt="Brand Image" width="170" height="100"></a></div>
						<div class="item"><a title="Brand 1" href="#"><img class="mark-lazy" src="{{media url="wysiwyg/brands/item-4.jpg"}}" alt="Brand Image" width="170" height="100"></a></div>
						<div class="item"><a title="Brand 1" href="#"><img class="mark-lazy" src="{{media url="wysiwyg/brands/item-5.jpg"}}" alt="Brand Image" width="170" height="100"></a></div>
						<div class="item"><a title="Brand 1" href="#"><img class="mark-lazy" src="{{media url="wysiwyg/brands/item-6.jpg"}}" alt="Brand Image" width="170" height="100"></a></div>
						<div class="item"><a title="Brand 1" href="#"><img class="mark-lazy" src="{{media url="wysiwyg/brands/item-1.jpg"}}" alt="Brand Image" width="170" height="100"></a></div>
						<div class="item"><a title="Brand 1" href="#"><img class="mark-lazy" src="{{media url="wysiwyg/brands/item-2.jpg"}}" alt="Brand Image" width="170" height="100"></a></div>
					</div>
					
					<div class="loading-content"><span class="hidden">Loading...</span></div>
				</div>
			</div>
		</div>
		
		<div class="block-news" style="margin-bottom: 50px;">
			<div class="nav-style-2">
				<div data-owl="owl-slider" data-autoplay="false" data-nav="true" data-dots="false" data-screen0="1" data-screen481="2" data-screen768="3" data-screen992="3" data-screen1200="4" data-screen1441="4" data-screen1681="4" data-screen1920="4" data-margin="30" data-autoplayhoverpause="true" data-loop="false" data-center="false" data-stagepadding="0" data-mousedrag="true" data-touchdrag="true">
					{{widget type="Magefan\Blog\Block\Widget\Recent" title="Latest News" number_of_posts="6" category_id="0" tag_id="0" author_id="0" custom_template="Magefan_Blog::widget/recent-slider.phtml" type_name="Recent Blog Posts"}}
				</div>
			</div>
		</div>
	</div>
	
	<div class="testimonial-full" style="background-color: #f9f9f9; padding: 40px 0 35px;">
		<div class="container">
			<div class="testimonial-slider hover-to-show">
				<div class="nav-style-3 nav-position-center">
					<div data-owl="owl-slider" data-autoplay="false" data-nav="true" data-dots="false" data-screen0="1" data-screen481="1" data-screen768="1" data-screen992="1" data-screen1200="1" data-screen1441="1" data-screen1681="1" data-screen1920="1" data-margin="30" data-autoplayhoverpause="true" data-loop="false" data-center="false" data-stagepadding="0" data-mousedrag="true" data-touchdrag="true">
						<div class="owl-carousel owl-theme">
							<div class="item">
								<div class="client-image">
									<img class="mark-lazy" src="{{media url="wysiwyg/clients/item-1.jpg"}}" alt="Client Image" width="90" height="90">
								</div>
								
								<div class="client-info">
									<div class="client-say">
										Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
									</div>
									
									<div class="client-name">Johny Walker</div>
								</div>
							</div>
							
							<div class="item">
								<div class="client-image">
									<img class="mark-lazy" src="{{media url="wysiwyg/clients/item-1.jpg"}}" alt="Client Image" width="90" height="90">
								</div>
								
								<div class="client-info">
									<div class="client-say">
										Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
									</div>
									
									<div class="client-name">Johny Walker</div>
								</div>
							</div>
							
							<div class="item">
								<div class="client-image">
									<img class="mark-lazy" src="{{media url="wysiwyg/clients/item-1.jpg"}}" alt="Client Image" width="90" height="90">
								</div>
								
								<div class="client-info">
									<div class="client-say">
										Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
									</div>
									
									<div class="client-name">Johny Walker</div>
								</div>
							</div>
						</div>
						
						<div class="loading-content"><span class="hidden">Loading...</span></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
