<style>
.footer-top {
background-color: #fff;
}
</style>
<div class="footer-top">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-sm-6">
				<div class="block-footer block-footer-contact">
					<div class="block-footer-title">Contact Us</div>
					
					<div class="block-footer-content footer-contact">
						<ul>
							<li class="address">5611 Wellington Road, Suite 115, Gainesville, VA 20155</li>
							<li class="phone">888 9344 6000 - 888 1234 6789</li>
							<li class="email">magentechservice@gmail.com</li>
							<li class="time">7 Days a week from 10-00 am to 6-00 pm</li>
						</ul>
					</div>
				</div>
			</div>
			
			<div class="col-lg-2 col-sm-6">
				<div class="block-footer block-links">
					<div class="block-footer-title">Information</div>
					
					<div class="block-footer-content">
						<ul>
							<li><a href="#">Shipping &amp; Returns</a></li>
							<li><a href="#">Secure Shopping</a></li>
							<li><a href="#">Order Status</a></li>
							<li><a href="#">International Shipping</a></li>
							<li><a href="#">Payment Method</a></li>
							<li><a href="{{store url=""}}about-us.html">About Us</a></li>
						</ul>
					</div>
				</div>
			</div>
			
			<div class="col-lg-2 col-sm-6">
				<div class="block-footer block-links">
					<div class="block-footer-title">Our Services</div>
					
					<div class="block-footer-content">
						<ul>
							<li><a href="#">Privacy Policy</a></li>
							<li><a href="#">Customer Service</a></li>
							<li><a href="#">Orders and Returns</a></li>
							<li><a href="{{store url=""}}contact">Contact Us</a></li>
							<li><a href="#">Track Your Orders</a></li>
							<li><a href="#">Footer Links</a></li>
						</ul>
					</div>
				</div>
			</div>
			
			<div class="col-lg-4 col-sm-6">
				<div class="block-footer newsletter-footer">
					<div class="block-footer-title">Sign up for Newsletter</div>
					
					<div class="block-footer-content">
						{{block class="Magento\Newsletter\Block\Subscribe" template="subscribe-footer.phtml"}}
					</div>
				</div>
				
				<div class="block-footer social-footer">
					<div class="block-footer-title">Connect us with</div>
					
					<div class="block-footer-content">
						<div class="social-footer">
							<ul>
								<li class="facebook"><a class="icon-facebook" title="Facebook" href="https://www.facebook.com/MagenTech"> <span class="hidden">Facebook</span> </a></li>
								<li class="youtube"><a class="icon-youtube1" title="Youtube" href="https://www.youtube.com/user/smartaddons"> <span class="hidden">Youtube</span> </a></li>
								<li class="twitter"><a class="icon-twitter" title="Twitter" href="https://twitter.com/MagenTech"> <span class="hidden">Twitter</span> </a></li>
								<li class="instagram"><a class="icon-instagram" title="Instagram" href="#"> <span class="hidden">Instagram</span> </a></li>
								<li class="linkedin"><a class="icon-linkedin" title="Linkedin" href="https://www.linkedin.com/in/magentech/"> <span class="hidden">Linkedin</span> </a></li>
								<li class="linkedin"><a class="icon-rss" title="RSS" href="#"> <span class="hidden">RSS</span> </a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
