<style>
/*
    Footer
*/
.footer-links {
    padding: 7px 0;
}
.footer-logo {
    width: 150px;
}
.footer-columns {
    max-width: 290px;
}
.footer-links {
    color: #fff;
    opacity: 0.8;
}
.btn-outline-orange  {
    background: transparent;
    border: 1px solid #ed9b2c;
}
.bg-gray-darker {
    background-color: #363636;
}
</style>
<div class="footer-top">
	<div class="container">
		<div class="row">
        <div class="footer-section bg-gray-darker text-white w-100">
                <div class="footer-wrapper d-flex justify-content-between mx-100">
                    <div class="footer-columns">
                        <div class="logo mb-5">
                            <a href="#"><img src="{{media url=&quot;assets/logo.png&quot;}}" class="footer-logo"></a>
                        </div>
                        <div>
                            info@toucango.com.au
                        </div>
                        <div>
                            Copyright @ <span class="text-orange">Toucango</span> 2020
                        </div>
                    </div>
                    <div class="footer-columns">
                        <div class="footer-links-heading mb-3"><strong>Links</strong></div>
                        <div class="footer-links">Advertise with us</div>
                        <div class="footer-links">About Us</div>
                        <div class="footer-links">Order Status</div>
                        <div class="footer-links">International Shipping</div>
                        <div class="footer-links">Payment Method</div>
                        <div class="footer-links">Privacy policy</div>
                    </div>
                    <div class="footer-columns">
                        <div class="footer-links-heading mb-3"><strong>Shopping</strong></div>
                        <div class="footer-links">Cookie Policy</div>
                        <div class="footer-links">Vendor code of conduct</div>
                        <div class="footer-links">Terms and conditions</div>
                        <div class="footer-links">Contact Us</div>
                    </div>
                    <div class="footer-columns">
                        <div class="footer-links-heading mb-3">Contact Us</div>
                        <div class="footer-links mb-3">Get in touch with us via mail phone. We are waiting for your call or message.</div>
                        <div class="mb-3"><button class="btn btn-outline-orange text-orange w-100" type="submit">Contact Now</button></div>
                        <div class="d-flex">
                            <div class="mx-3 m-2"><i class="fab fa-facebook-f"></i></div>
                            <div class="mx-3 m-2"><i class="fab fa-twitter"></i></div>
                            <div class="mx-3 m-2"><i class="fab fa-facebook-f"></i></div>
                            <div class="mx-3 m-2"><i class="fab fa-facebook-f"></i></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>
